language: elixir
elixir:
  - 1.5.3
  - 1.6.6
  - 1.7.4
  - 1.8.2
sudo: false # to use faster container based build environment
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
otp_release:
  - 19.3
  - 20.3
  - 21.3
  - 22.0
script:
  - if [[ $(elixir --version) = *"1.6"* ]]; then mix format --check-formatted; fi
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
matrix:
  exclude:
    - elixir: 1.5.3
      otp_release: 21.3
    - elixir: 1.5.3
      otp_release: 22.0
    - elixir: 1.6.6
      otp_release: 22.0
    - elixir: 1.8.2
      otp_release: 19.3
